stages:
  fetch_ev:
    cmd: |
      poetry run python src/data/fetch_ev_data.py
      git commit -am "⚡ Updated raw EV data on $(date) with DVC pipeline" || true
      git push || true
      dvc push || true
    deps:
      - src/data/fetch_ev_data.py
    outs:
      - data/raw/ev/ljubljana_ev_availability_combined.json
    always_changed: true

  preprocess_ev:
    cmd: |
      poetry run python src/data/preprocess_ev_data.py
      git commit -am "🧹 Preprocessed EV data on $(date) with DVC pipeline" || true
      git push || true
      dvc push || true
    deps:
      - src/data/preprocess_ev_data.py
      - data/raw/ev/ljubljana_ev_availability_combined.json
    outs:
      - data/preprocessed/ev:
          persist: true

  validate_ev_data:
    cmd: |
      cd gx && poetry run python run_checkpoint.py
    deps:
      - data/preprocessed/ev/
      - gx/run_checkpoint.py
      - gx/great_expectations.yml
    outs:
      - gx/uncommitted:
          persist: true

  test_ev_data:
    cmd: |
      poetry run python src/data/test_ev_data.py
    deps:
      - src/data/test_ev_data.py
      - data/preprocessed/ev
    outs:
      - reports/ev_drift:
          persist: true

  train_ev:
    cmd: |
      poetry run python src/model/train_ev.py
      git commit -am "🤖 Trained EV model on $(date) via DVC pipeline" || true
      git push || true
      dvc push || true
    deps:
      - src/model/train_ev.py
      - src/model/preprocess.py
      - data/preprocessed/ev
      - gx/uncommitted
      - reports/ev_drift
    params:
      - train_ev.test_size
      - train_ev.random_state
      - train_ev.window_size
      - train_ev.freq
      - train_ev.target
    outs:
      - models/:
          persist: true

  export_and_deploy_frontend:
    cmd: scripts/export_frontend.sh
    deps:
      - src/model/export_mlflow_models.py
      - scripts/export_frontend.sh
    outs:
      - public/ml_models.json
    always_changed: true

  upload_reports:
    cmd: bash scripts/upload_reports.sh
    deps:
      - reports/ev_drift/
      - gx/uncommitted/data_docs/local_site/expectations/
      - scripts/upload_reports.sh
