name: ⚡ Fast EV Data Pipeline (Every 1 hour)

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  fetch_and_preprocess:
    name: Fetch and preprocess EV data
    runs-on: ubuntu-latest

    environment:
      name: master-push-lock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Install DVC
        run: pip install dvc[s3]

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: poetry

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: DVC setup remote
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_SECRET_ACCESS_KEY }}

      - name: DVC pull & status
        run: |
          dvc pull --force
          dvc status

      - name: Run fast DVC stages
        env:
          TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          dvc repro fetch_ev preprocess_ev validate_ev_data test_ev_data upload_reports
          dvc push
          git add .
          git commit -m "🧹 Auto-update EV data pipeline on $(date)" || true
          git pull --rebase
          git push || echo "Skipped push due to conflict"
