name: Fetch EV data on schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  fetch_ev:
    name: Fetch and pre-process EV data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: poetry

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
        with:
          version: '3.51.0'

      - name: Install dependencies
        run: poetry install --no-root --no-interaction

      - name: DVC remote setup
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_SECRET_ACCESS_KEY }}

      - name: Run DVC pipeline
        env:
          TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}
        run: |
          dvc pull
          dvc repro
          dvc push
          git add dvc.lock
          git commit -m "🔌 Update EV data pipeline on $(date) via GitHub Actions" || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
