name: 🤖 Full EV Model Training (Every 6 Hours from 09:00 UTC)

on:
  schedule:
    - cron: '0 9,15,21,3 * * *'  # 🕘 09:00, 15:00, 21:00, 03:00 UTC daily
  workflow_dispatch:

jobs:
  train_model_and_export:
    name: Train model and deploy metadata
    runs-on: ubuntu-latest

    environment:
      name: master-push-lock  # 🔒 avoid conflict with other workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Install DVC
        run: pip install dvc[s3]

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: poetry

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: DVC setup remote
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_SECRET_ACCESS_KEY }}

      - name: DVC pull & status
        run: |
          dvc pull --force
          dvc status

      - name: Run only train_ev and export_and_deploy_ml_json
        env:
          TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          dvc repro --single-item train_ev
          dvc repro --single-item export_and_deploy_ml_json
          dvc push
          git add .
          git commit -m "🤖 Full model training run on $(date)" || true
          git pull --rebase
          git push || echo "Skipped push due to conflict"
